Description: >
  Contains AWS CodeBuild and AWS CodePipeline, with Java and Docker build steps.

Parameters:
  ContainerName:
    Type: String
    Description: Unique name for the Docker instance.

  LoadBalancerName:
    Type: String
    Description: The name to give the load balancer DNS. Must be unique in your account.
    MinLength: 4
    MaxLength: 32
    AllowedPattern: ^[A-Za-z0-9\-]*$
    ConstraintDescription: >
     Load balancer name must be unique, more than 4 characters, less than 33 characters and only include letters and numbers.

  InstanceType:
    Type: String
    Default: t2.small
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge, m3.medium, m3.large, m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge, m4.16xlarge]
    Description: The size of the instance host that will run the Docker images.

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  SplunkToken:
    Type: String
    Description: This is the token to log on the Splunk cloud

  SplunkUrl:
    Type: String
    Description: This is the API for Splunk, generally on 8088

  S3Region:
    Type: String
    Default: "us-west-2"
    AllowedValues : ["us-west-2", "us-west-1", "ap-south-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1"]
    Description: S3 Region where bucket resides (us-west-2 is Oregon)

  S3TemplateBucket:
    Type: String
    Description: S3 Bucket containing templates.zip (requires versioning on)

  GitHubUser:
    Type: String
    Description: The GitHub owner/organisation of the repo to build.

  GitHubRepo:
    Type: String
    Default: TechemyLtd/bnc-market-cache-service
    Description: The repo name of the sample service.

  GitHubBranch:
    Type: String
    Default: master
    Description: The branch of the repo to continuously deploy.

  GitHubToken:
    Type: String
    Description: >
      Token for the user specified above. (https://github.com/settings/tokens)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      ContainerName:
        default: "Container name"
      LoadBalancerName:
        default: "Load balancer DNS name"
      KeyName:
        default: "AWS SSH KeyName"
      InstanceType:
        default: "AWS Instance type"
      GitHubUser:
        default: "Owner"
      GitHubRepo:
        default: "Repo"
      GitHubBranch:
        default: "Branch"
      GitHubToken:
        default: "Personal Access Token"
      S3TemplateBucket:
        default: "S3 Template Bucket"
      S3Region:
        default: "S3 Region"
    ParameterGroups:
      - Label:
          default: AWS container stuff
        Parameters:
          - ContainerName
          - LoadBalancerName
          - KeyName
          - InstanceType
      - Label:
          default: Splunk stuff
        Parameters:
          - SplunkToken
          - SplunkUrl
      - Label:
          default: S3 Configuration
        Parameters:
          - S3TemplateBucket
          - S3Region
      - Label:
          default: GitHub Configuration
        Parameters:
          - GitHubRepo
          - GitHubBranch
          - GitHubUser
          - GitHubToken

Resources:
  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${S3Region}.amazonaws.com/${S3TemplateBucket}/templates/ecs-cluster.yaml
      Parameters:
        KeyName: !Ref KeyName
        InstanceType: !Ref InstanceType
        ElasticLoadBalancer: !Ref LoadBalancerName
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId
        ContainerName: !Ref ContainerName

  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${S3Region}.amazonaws.com/${S3TemplateBucket}/templates/deployment-pipeline.yaml
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        TargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        TemplateBucket: !Ref S3TemplateBucket
        SplunkToken: !Ref SplunkToken
        SplunkUrl: !Ref SplunkUrl
        ContainerName: !Ref ContainerName

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${S3Region}.amazonaws.com/${S3TemplateBucket}/templates/load-balancer.yaml
      Parameters:
        ElasticLoadBalancer: !Ref LoadBalancerName
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${S3Region}.amazonaws.com/${S3TemplateBucket}/templates/vpc.yaml
      Parameters:
        Name: !Ref AWS::StackName
        VpcCIDR: 10.215.0.0/16
        Subnet1CIDR: 10.215.10.0/24
        Subnet2CIDR: 10.215.20.0/24


Outputs:
  ServiceUrl:
    Description: Public URL for the loadbalancer.
    Value: !GetAtt LoadBalancer.Outputs.ServiceUrl

  PipelineUrl:
    Description: The continuous deployment build pipeline.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl
